use nullledge;
drop TABLE `NULLLEDGE`.`LIKE_LOG_TB`;
drop TABLE `NULLLEDGE`.`FILE_TB`;
drop TABLE `NULLLEDGE`.`TAG_TB`;
drop TABLE `NULLLEDGE`.`POST_TB`;
drop TABLE `NULLLEDGE`.`PROBLEM_SET_TB`;
drop TABLE `NULLLEDGE`.`MYSOLVED_TB`;
drop TABLE `NULLLEDGE`.`USER_TB`;
