-- USER_TB
CREATE TABLE `NULLLEDGE`.`USER_TB` (
  `USER_NM` VARCHAR(45) NOT NULL,
  `GMAIL_NM` VARCHAR(45) NOT NULL,
  `GMAIL_TOKEN_NM` VARCHAR(45) NOT NULL,
  `SOL_TOKEN_NM` VARCHAR(45) NOT NULL,
  `BOJ_ID` VARCHAR(45) NULL,
  `AUTHORITHY_NM` VARCHAR(45) NULL,
  `ASKED_AMT` INT NOT NULL,
  `POST_CNT` INT NOT NULL,
  `REPLY_CNT` INT NOT NULL,
  `LIKE_CNT` INT NOT NULL,
  `NULLPOINT_AMT` INT NOT NULL,
  `SIGNUP_YMD` DATETIME NOT NULL,
  PRIMARY KEY (`USER_NM`));

-- MYANSWERED_TB
CREATE TABLE `NULLLEDGE`.`MYANSWERED_TB` (
  `USER_NM` VARCHAR(45) NOT NULL,
  `DP_ANS_AMT` INT NOT NULL,
  `GRAPHS_ANS_AMT` INT NOT NULL,
  `DS_ANS_AMT` INT NOT NULL,
  `GREEDY_ANS_AMT` INT NOT NULL,
  `BRUTE_FORCE_ANS_AMT` INT NOT NULL,
  `BINARY_SEARCH_ANS_AMT` INT NOT NULL,
  `SORT_ANS_AMT` INT NOT NULL,
  `STRING_ANS_AMT` INT NOT NULL,
  `ETC_ANS_AMT` INT NOT NULL,
  PRIMARY KEY (`USER_NM`));

-- MYSOLVED_TB
CREATE TABLE `NULLLEDGE`.`MYSOLVED_TB` (
  `USER_NM` VARCHAR(45) NOT NULL,
  `DP_AMT` INT NOT NULL,
  `GRAPHS_AMT` INT NOT NULL,
  `DS_AMT` INT NOT NULL,
  `GREEDY_AMT` INT NOT NULL,
  `BRUTE_FORCE_AMT` INT NOT NULL,
  `BINARY_SEARCH_AMT` INT NOT NULL,
  `SORT_AMT` INT NOT NULL,
  `STRING_AMT` INT NOT NULL,
  `ETC_AMT` INT NOT NULL,
  PRIMARY KEY (`USER_NM`));

-- POST_TB
CREATE TABLE `NULLLEDGE`.`POSTS_TB` (
  `POST_ID` INT NOT NULL,
  `PROBLEM_ID` INT NULL,
  `USER_NM` VARCHAR(45) NOT NULL,
  `POST_NM` VARCHAR(70) NOT NULL,
  `POST_YMD` DATETIME NOT NULL,
  `POST_TAGS_NM` JSON NULL,
  `POST_CONTENT` TEXT NOT NULL,
  `LIKE_CNT` INT NOT NULL,
  `VIEW_CNT` INT NOT NULL,
  PRIMARY KEY (`POST_ID`));

-- FILE_TB
CREATE TABLE `NULLLEDGE`.`FILE_TB` (
  `FILE_ID` INT NOT NULL,
  `USER_NM` VARCHAR(45) NOT NULL,
  `POST_ID` INT NULL,
  `REPLY_POST_ID` INT NULL,
  `FILE_NM` VARCHAR(45) NOT NULL,
  `FILE_PATH` VARCHAR(45) NOT NULL,
  `FILE_TYPE` VARCHAR(45) NOT NULL,
  `FILE_SIZE` DOUBLE NOT NULL,
  PRIMARY KEY (`FILE_ID`));

-- PROBLEM_SET_TB
CREATE TABLE `NULLLEDGE`.`PROBLEM_SET_TB` (
  `PROBLEM_ID` INT NOT NULL,
  `TAGS_NM` TEXT NOT NULL,
  `SOLVED_USR` JSON NULL,
  `HASH_ID` int NOT NULL,
  PRIMARY KEY (`PROBLEM_ID`));

-- COMMENT_TB
CREATE TABLE `NULLLEDGE`.`COMMENT_TB` (
  `COMMENT_ID` INT NOT NULL,
  `POST_ID` INT NULL,
  `REPLY_POST_ID` INT NULL,
  `LIKE_CNT` INT NOT NULL,
  `COMMENT_CONTENT` TEXT NOT NULL,
  PRIMARY KEY (`COMMENT_ID`));

-- REPLY_POST_TB
CREATE TABLE `NULLLEDGE`.`REPLY_POST_TB` (
  `REPLY_POST_ID` INT NOT NULL,
  `POST_ID` INT NOT NULL,
  `LIKE_CNT` INT NOT NULL,
  `REPLY_CONTENT` TEXT NOT NULL,
  PRIMARY KEY (`REPLY_POST_ID`));


