-- USER_TB
CREATE TABLE `NULLLEDGE`.`USER_TB` (
	`USER_ID` INT NOT NULL,
	`GMAIL_NM` VARCHAR(45) NOT NULL,
	`USER_NICK_NM` VARCHAR(45) NOT NULL,
	`GMAIL_TOKEN_NM` VARCHAR(45) NOT NULL,
	`SOL_TOKEN_NM` VARCHAR(45) NOT NULL,
	`BOJ_ID` VARCHAR(45) NULL,
	`AUTHORITHY_AMT` INT NULL,
	`ASKED_AMT` INT NOT NULL,
	`REPLY_AMT` INT NOT NULL,
	`LIKE_CNT` INT NOT NULL,
	`NULLPOINT_AMT` INT NOT NULL,
	`SIGNUP_YMD` TIMESTAMP NOT NULL,
	PRIMARY KEY (`USER_ID`)
);

-- PROBLEM_SET_TB
CREATE TABLE `NULLLEDGE`.`PROBLEM_SET_TB` (
	`PROBLEM_ID` INT NOT NULL,
	`TITLE_NM` VARCHAR(70) NOT NULL,
	`TAGS_NM` JSON NOT NULL,
	`SOLVED_USR` JSON NULL,
	`HASH_ID` INT NOT NULL,
	PRIMARY KEY (`PROBLEM_ID`)
);
  
  
-- MYSOLVED_TB
CREATE TABLE `NULLLEDGE`.`MYSOLVED_TB` (
	`USER_ID` INT NULL,
	`DP_AMT` INT NULL,
	`GRAPHS_AMT` INT NULL,
	`DS_AMT` INT NULL,
	`GREEDY_AMT` INT NULL,
	`BRUTE_FORCE_AMT` INT NULL,
	`BINARY_SEARCH_AMT` INT NULL,
	`SORT_AMT` INT NULL,
	`STRING_AMT` INT NULL,
	`ETC_AMT` INT NULL,
	FOREIGN KEY (`USER_ID`) REFERENCES `NULLLEDGE`.`USER_TB` (`USER_ID`)
);


-- POSTS_TB
CREATE TABLE `NULLLEDGE`.`POSTS_TB` (
	`POST_ID` INT NOT NULL PRIMARY KEY,
    `PROBLEM_ID` INT NULL,
    `USER_ID` INT NULL,
    `TYPE_GB` INT NOT NULL,
    `POST_NM` VARCHAR(70) NOT NULL,
    `POST_YMD` TIMESTAMP NOT NULL,
    `POST_TAGS_NM` JSON NOT NULL,
    `CONTENT` TEXT NULL,
    `VIEW_CNT` INT NOT NULL,
    `PARENT_POST_ID` INT NULL,
    `KIND_POINT_AMT` INT NULL,
    FOREIGN KEY (`POST_ID`) REFERENCES `NULLLEDGE`.`USER_TB` (`USER_ID`),
    FOREIGN KEY (`PROBLEM_ID`) REFERENCES `NULLLEDGE`.`PROBLEM_SET_TB` (`PROBLEM_ID`)
);

-- LIKE_LOG_TB
CREATE TABLE `NULLLEDGE`.`LIKE_LOG_TB` (
	`USER_ID` INT NOT NULL,
	`POST_ID` INT NOT NULL,
    `LOG_YMD` TIMESTAMP NOT NULL,
    FOREIGN KEY (`USER_ID`) REFERENCES `NULLLEDGE`.`USER_TB` (`USER_ID`),
    FOREIGN KEY (`POST_ID`) REFERENCES `NULLLEDGE`.`POSTS_TB` (`POST_ID`)
);

-- FILE_TB
CREATE TABLE `NULLLEDGE`.`FILE_TB` (
	`FILE_ID` INT NOT NULL PRIMARY KEY,
    `USER_ID` INT NOT NULL,
    `POST_ID` INT NOT NULL,
    `FILE_NM` VARCHAR(45) NOT NULL,
    `FILE_PATH` VARCHAR(45) NOT NULL,
    `FILE_TYPE` VARCHAR(45) NOT NULL,
    `FILE_SIZE` DOUBLE NOT NULL,
    FOREIGN KEY (`USER_ID`) REFERENCES `NULLLEDGE`.`USER_TB` (`USER_ID`),
    FOREIGN KEY (`POST_ID`) REFERENCES `NULLLEDGE`.`POSTS_TB` (`POST_ID`)
);